modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/kel-cu/waterplayer/issues"
license="GPL 3.0"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "waterplayer"
version = "${version}"
displayURL = "https://modrinth.com/mod/waterplayer"
displayName = "WaterPlayer"
updateJSONURL = "https://api.modrinth.com/updates/waterplayer/forge_updates.json"
authors = "Kel Cuprum"
description = "Internet music player built into the client."
logoFile = "assets/waterplayer/logo.png"

[[dependencies.waterplayer]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.waterplayer]]
modId = "alinlib"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.waterplayer]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"